name: "RDComponents"

############
# Options
############

settings:
  GENERATE_INFOPLIST_FILE: NO
  CODE_SIGNING_ALLOWED: NO

options:
  bundleIdPrefix: com.rappidriver
  minimumXcodeGenVersion: 2.10
  groupSortPosition: top
  generateEmptyDirectories: true
  deploymentTarget: 
    iOS: "14.0"

############
# Targets
############

targets:
  RDComponents:
    type: framework
    supportedDestinations: [iOS]
    platform: iOS
    deploymentTarget: "14.0"
    sources:
      - Sources
    scheme:
      testTargets:
        - RDComponentsTests
      gatherCoverageData: true
      coverageTargets:
        - RDComponents
    # preBuildScripts:
    #   - name: "Lint"
    #     script: | 
    #       if which swiftlint > /dev/null; then
    #         swiftlint
    #       else
    #         echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
    #       fi
  RDComponentsTests:
    sources: 
      - Tests
  #     - path: Sources/RDCompomemts/Resources/Strings
  #       buildPhase: resources
    type: bundle.unit-test
    platform: iOS
    info:
      path: Tests/Info.plist
    dependencies:
      - target: RDComponents
    # scheme:
    #   testTargets:
    #     - RDCompomemtsTests
      # gatherCoverageData: true
scheme:
  RDComponents:
    build:
      targets:
        RDComponents: all
        RDComponentsTests: [test]
    test:
      language: pt
      gatherCoverageData: true
      coverageTargets:
        - RDComponents
      targets: 
        - name: RDComponentsTests
          parallelizable: true
  RDComponentsTests:
    build:
      targets: 
        RDComponentsTests: [test]