name: "RDComponents"

############
# Options
############

options:
  minimumXcodeGenVersion: 2.10
  groupSortPosition: top
  generateEmptyDirectories: true
  deploymentTarget: 
    iOS: "13.0"

############
# Targets
############

targets:
  RDComponents:
    type: framework
    platform: iOS
    sources:
      - Sources
    # preBuildScripts:
    #   - name: "Lint"
    #     script: | 
    #       if which swiftlint > /dev/null; then
    #         swiftlint
    #       else
    #         echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
    #       fi
  # OnboardingTests:
  #   type: bundle.unit-test
  #   platform: [iOS]
  #   sources:
  #     - Tests
  #   dependencies:
  #     - target: Onboarding