# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: build

on:
  workflow_call:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "main", "develop" ]


jobs:
  build_job:
    name: Build Job
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Xcodegen
      run: brew install xcodegen
    - name: Run Xcodegen
      run: xcodegen
    - name: Build
      run: xcodebuild -scheme RDComponents -destination "name=iPhone 14" | xcpretty
    - name: Run tests
      run: xcodebuild -scheme RDComponents test -destination "name=iPhone 14" | xcpretty