# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run Xcodegen
      run: xcodegen
    - name: Build
      run: xcodebuild -scheme RDComponents -destination "name=iPhone 11" | xcpretty
    - name: Run tests
      run: xcodebuild -scheme RDComponents test -destination "name=iPhone 11" | xcpretty
